# **Taller Práctico 03 — Inteligencia Geo-Temporal y de Redes**

## Optimización de Activos Críticos

**Maestría en Ciencia de Datos y Analítica — Universidad EAFIT**  
Curso: Fundamentos en Ciencia de Datos | Docente: Jorge Iván Padilla-Buriticá
Periodo académico 2026-2

## Fase 1: Data Understanding y Geo-Visualización

### Tarea 1: Exploración Geo-Temporal

In [ ]:
import pandas as pd 
import plotly.express as px
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller

In [5]:
## Carga datos

df_agro = pd.read_csv(r'..\data\raw\agro\agro_clean.csv')
df_ener = pd.read_csv(r'..\data\raw\ener\ener_clean.csv')
df_agro

,Agro_1,Agro_2,Agro_3,Agro_4,Agro_5,Agro_6,Agro_7,Agro_8,Agro_9,Agro_10,Latitude,Longitude,Source_Node,Target_Node
0,60.248357,47.797447,65.395554,0.000000,0.478718,2.498349,10.000000,6.432151,1.258741,4.663639,6.203680,-75.400366,4,17
1,60.080940,48.076702,66.143237,25.002075,0.467100,2.473166,10.006672,6.469450,1.106051,4.683748,6.282310,-75.474525,14,21
2,60.623974,48.002378,66.342755,49.941596,0.449259,2.464547,10.013349,6.440262,1.183610,8.353141,6.165190,-75.476937,14,22
3,61.211672,48.267738,66.826015,74.756163,0.439299,2.500284,10.020030,6.511042,1.197917,6.213966,6.131334,-75.468152,8,25
4,60.483063,47.912028,65.703353,99.383693,0.436016,2.564177,10.026716,6.619718,1.200795,8.720976,6.241746,-75.349805,5,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,73.973383,58.759183,80.902167,0.000000,2.252759,2.893555,37.835599,6.381881,1.230914,5.705589,6.244438,-75.388452,11,16
1996,73.491049,58.180104,81.661594,0.000000,2.260299,2.793638,37.860844,6.492718,1.220833,6.785542,6.270976,-75.430809,14,27
1997,73.128022,58.759078,80.073673,0.000000,2.244597,2.758372,37.886105,6.583801,1.180722,4.575810,6.177446,-75.416718,4,21
1998,73.550718,59.398815,81.323042,0.000000,2.278655,2.783160,37.911384,6.489930,1.209546,5.982033,6.122933,-75.340495,13,22
1999,73.321727,59.063537,80.244400,0.000000,2.321211,2.815380,37.936679,6.405369,1.205357,5.847800,6.268491,-75.467578,10,26

In [3]:
##*scatter_mapbox* is deprecated! Use *scatter_map* instead

In [ ]:
fig = px.scatter_map(
    df_agro, 
    lat="Latitude", 
    lon="Longitude",
    color="Agro_5", 
    size="Agro_1",
    zoom=10,
    # title="Scatter Map"
)

# Apply free map tile layers so you do not need a token
# fig.update_layout(mapbox_style="open-street-map")
fig.show()

Análisis: ¿Existe algún patrón espacial (clustering) donde la biomasa sea consistentemente baja?

### Tarea 2: Análisis de Estacionariedad y Windowing

In [6]:
df_ener

,Ener_1,Ener_2,Ener_3,Ener_4,Ener_5,Ener_6,Ener_7,Ener_8,Ener_9,Ener_10,Latitude,Longitude,Source_Node,Target_Node
0,117.538413,169.976747,31.052273,40.000000,5.035559,999.997980,500.382001,60.007129,109.525783,0.952104,6.772983,-75.450170,106,244
1,123.085137,178.287791,30.367913,40.001201,4.964209,1000.012288,499.156777,60.010171,109.396517,0.963803,6.817829,-76.987525,113,241
2,122.444639,178.064846,29.483741,40.004804,4.885030,1000.185140,499.276252,59.998643,110.560808,0.939290,5.519644,-73.757957,105,233
3,117.595897,175.257364,29.985873,40.010804,5.039720,1000.075905,499.093300,59.994357,109.234773,0.945306,8.788327,-73.611230,105,237
4,123.471177,186.082293,30.359202,40.019198,5.046006,999.714688,499.380771,59.955593,110.202660,0.951658,8.450681,-73.456254,108,206
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,86.323567,128.336394,22.475277,22.051886,26.150812,803.439528,540.589156,60.005521,109.382291,0.946502,8.456787,-72.453955,106,218
1996,91.342886,132.183280,21.312438,22.297509,26.168797,803.378768,539.852136,59.981609,111.213778,0.947118,5.128314,-76.623466,106,249
1997,87.557997,137.318341,22.037410,22.551272,26.154045,803.187891,539.885870,59.974251,109.738614,0.946081,8.901269,-74.100966,116,208
1998,92.630345,129.440422,22.130496,22.813095,26.140720,803.124892,540.535321,59.974938,110.126092,0.948870,10.001202,-72.309228,106,224
1999,90.619463,135.550462,22.736793,23.082895,26.145452,802.709465,540.643262,59.982087,109.659974,0.939597,8.602569,-73.781321,112,221

## Fase 2: Procesamiento de Señales y Filtrado

### Tarea 3: Análisis Espectral (FFT) y Espectrogramas

### Tarea 4: Filtrado y Reconstrucción

## Fase 3: Análisis de Grafos y Topología de Red

### Tarea 5: Construcción de la Red de Sensores/Subestaciones

## Fase 4: Modelado y Toma de Decisiones (CRISP-DM)

### Problema de Negocio: La Falla del Nodo 214